### ISSUE TITLE
Installation Error [ ImportError: libnccl.so.2: cannot open shared object file: No such file or directory ]

### ISSUE THREAD

**Issue by GeorgeAdamon** [zju3dv/GVHMR#14]
Hello and thank you for a great project!

I am running into a persistent installation issue on Ubuntu running on WSL 2 (Ubuntu 22.04.3 LTS).

I follow the [instructions ](https://github.com/zju3dv/GVHMR/blob/main/docs/INSTALL.md) **_exactly_**, but when i run the last line for DVPO `pip install -e .` I get this error:

```bash
WARNING: Ignoring invalid distribution -mcv (/home/ulc/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -mcv (/home/ulc/.local/lib/python3.10/site-packages)
Processing /home/ulc/GVHMR/third-party/DPVO
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ulc/GVHMR/third-party/DPVO/setup.py", line 3, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
        File "/home/ulc/anaconda3/envs/gvhmr/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
          from torch._C import *  # noqa: F403
      ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -mcv (/home/ulc/.local/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -mcv (/home/ulc/.local/lib/python3.10/site-packages)
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

CUDA 12.1 is properly installed by following the [official instructions](https://developer.nvidia.com/cuda-12-1-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local)

```bash
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.1.0/local_installers/cuda-repo-wsl-ubuntu-12-1-local_12.1.0-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-1-local_12.1.0-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda
```

The same error appears when I try to run the demo.py, even with a static cam (so it might not be DVPO related?)
```bash
Traceback (most recent call last):
  File "/home/ulc/GVHMR/tools/demo/demo.py", line 2, in <module>
    import torch
  File "/home/ulc/anaconda3/envs/gvhmr/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
```

Any help would be appreciated!

**Comment by GeorgeAdamon** [comment]
Thanks for your quick reply!

Same error
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ulc/anaconda3/envs/gvhmr/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
```

What is **_weird_** is that I have been running other projects similar to this in terms of dependencies without a problem (WHAM, 4D Humans, MMPose) all this week, in the same exact system configuration.

**Comment by GeorgeAdamon** [comment]
Aha!
I managed to make it work by installing pytorch 2.3.0 using the command provided by the [official site](https://pytorch.org/get-started/previous-versions/#linux-and-windows-5):
`conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=12.1 -c pytorch -c nvidia`

Everything works now.
