### ISSUE TITLE
Feature Request: Support NVIDIA Blackwell (RTX 50 Series GPUs, etc.)

### ISSUE THREAD

**Issue by StevenDean21st** [zju3dv/GVHMR#88]
目前项目依赖 torch 2.3，在 NVIDIA Blackwell 架构的 GPU（如 RTX 50 系列）上运行时会出现 CUDA 相关错误，无法正常执行。When running the project on NVIDIA GPUs with Blackwell architecture (e.g., RTX 50 series), CUDA-related errors occur and the project cannot execute normally.

**Comment by StevenDean21st** [comment]
运行过程中出现以下错误提示：
The following error message appears during execution:
```sh
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
```

**Comment by StevenDean21st** [comment]
由于项目自带的 requirements.txt 中指定的 PyTorch 版本过旧，不支持 Blackwell 架构，因此我未使用该文件安装依赖，而是通过以下 `conda` 和 `pip` 命令手动安装了兼容的依赖包：

Since the PyTorch version specified in the project's built-in requirements.txt is too old to support the Blackwell architecture, I did not use this file to install dependencies. Instead, I manually installed compatible dependency packages via the following conda and pip commands:

```sh
# ultralytics needs to upgrade to load models with weights_only
conda install pytorch torchvision ultralytics==8.4.6 pytorch3d==0.7.9 -c pytorch -c conda-forge
conda install ffmpeg-python timm==0.9.12 lightning==2.3.0 hydra-core==1.3 hydra-zen hydra-colorlog rich jupyter matplotlib ipdb black tensorboardx scikit-image einops imageio==2.34.1 av==13.0.0 joblib trimesh chumpy pycolmap -c conda-forge
# not found in conda-forge
pip install cython_bbox smplx wis3d lapx
```

完成依赖安装后，我测试了以下两个 demo ，均能成功运行且无报错：

After completing the dependency installation, I tested the following two demos, both of which ran successfully without errors:

```sh
python tools/demo/demo.py --video=docs/example_video/tennis.mp4 -s
python tools/demo/demo_folder.py -f docs/example_video -d outputs/demo/folder_out -s
```

**注意**：仅测试了上述两个 demo 功能，项目的其他功能暂未验证是否能正常运行。
**Please Note**: Only the above two demo functions were tested, and other functions of the project have not been verified to run normally.

**Comment by StevenDean21st** [comment]
## Update

I tested the previous solution again and found that it may still have some issues in certain environments.  
我重新测试了之前的方案，发现它在某些环境下可能仍然存在一些问题。

The main problems are:  
主要问题包括：

1. Some dependencies were not pinned to specific versions, which may still cause runtime errors.  
   部分依赖没有固定具体版本，运行时仍然可能出现问题。

2. PyTorch-related packages may be resolved to CPU builds by conda if the CUDA build is not explicitly specified.  
   如果没有显式指定 CUDA 版本，conda 可能会把 PyTorch 相关依赖解析成 CPU 版本。

3. Dependency solving can be very slow, especially when installing `pytorch3d`.  
   依赖解析速度可能会很慢，尤其是在安装 `pytorch3d` 时。

Below is the updated working installation method for GVHMR on Blackwell GPUs.  
下面是更新后的、已测试可用的 GVHMR 在 Blackwell GPU 上的安装方法。

## Install GVHMR on Blackwell / 在 Blackwell 上安装 GVHMR

```bash
# Enter the GVHMR directory
# 进入 GVHMR 目录
conda create -y -n gvhmr python=3.10
conda activate gvhmr

# Install prebuilt packages from conda-forge
# 直接下载 conda-forge 上编译好的包
#
# Adjust the CUDA version of pytorch3d if needed.
# 根据需要调整 pytorch3d 的 CUDA 版本。
#
# For example, for CUDA 12.8, use:
# 例如，如果要安装 CUDA 12.8 的版本，可以改为：
#   'pytorch3d=0.7.9=cuda128py310*'
#
# If the CUDA build is not specified, conda may resolve pytorch3d to the CPU version,
# which will cause runtime errors when GVHMR tries to use the GPU.
# 如果不加 CUDA 限制，conda 可能会解析成 CPU 版本，
# 导致 GVHMR 运行时调用 GPU 而报错。
#
# Available pytorch3d builds can be checked here:
# 可在此处查看有哪些 pytorch3d 版本：
# https://conda-metadata-app.streamlit.app/?q=conda-forge/pytorch3d
#
# Note: dependency solving may take a while.
# 注意：此处依赖解析速度可能较慢，耐心等待即可。
conda install \
  'pytorch==2.10.0' \
  'torchvision==0.25.0' \
  'ultralytics==8.4.52' \
  'pytorch3d=0.7.9=cuda130py310*' \
  'ffmpeg-python==0.2.0' \
  -c conda-forge

# Install the remaining dependencies
# 安装其他依赖
#
# numpy==1.23.5 fixes the chumpy error:
# numpy==1.23.5 可解决 chumpy 的如下错误：
#   ImportError: cannot import name 'int' from 'numpy'
#
# scikit-image should be pinned to 0.24.0 to remain compatible with numpy==1.23.5.
# 同时 scikit-image 需要固定为 0.24.0，以兼容 numpy==1.23.5。
#
# ultralytics-thop is optional and does not affect running the project,
# although `pip check` may still report that ultralytics requires ultralytics-thop.
# ultralytics-thop 视情况安装，不影响项目运行，
# 虽然 `pip check` 可能始终会提示 ultralytics 依赖 ultralytics-thop。
pip install \
  numpy==1.23.5 \
  timm==0.9.12 \
  lightning==2.3.0 \
  scikit-image==0.24.0 \
  hydra-core==1.3 \
  hydra-zen \
  hydra-colorlog \
  rich \
  jupyter \
  ipdb \
  black \
  tensorboardX \
  einops \
  av==13.0.0 \
  joblib \
  trimesh \
  smplx \
  wis3d \
  pycolmap \
  cython_bbox \
  lapx \
  chumpy

# Install GVHMR
# 安装 GVHMR
pip install -e . --no-deps
```

In addition, for newer PyTorch versions, `torch.load` may fail because of the default `weights_only` behavior when loading checkpoints.  
此外，对于较新的 PyTorch 版本，在加载 checkpoint 时，`torch.load` 可能会因为默认的 `weights_only` 行为而失败。

Open the following file:  
找到并打开以下文件：

```text
GVHMR/tools/demo/demo.py
```

Change:
将其中的：

```python
traj = torch.load(cfg.paths.slam)
```

to:
更改为：

```python
traj = torch.load(cfg.paths.slam, weights_only=False)
```

This fixes the checkpoint loading issue caused by the default parameter change in newer PyTorch versions.
这样可以处理高版本 PyTorch 加载 checkpoint 时由于默认参数变化导致的问题。

**Comment by Nagato-Yukii** [comment]
5070Ti(Driver Version: 580.95.05      CUDA Version: 13.0) 实测一遍过，太赞了
